version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: UTC
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: UTC
    labels:
      - dependencies
      - devcontainer

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: UTC
    labels:
      - dependencies
      - pre-commit
